# command for run this app : 
#         $ ~/google_appEngine/google_appengine/dev_appserver.py django_test/sample_project/

# command for deploy app :
#		  $ ~/google_appEngine/google_appengine/appcfg.py -A sample-django update django_test/sample_project/

application: sample-django
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: on

handlers:

- url: /static
  static_dir: static

- url: /.*
  script: main.application


libraries:

- name: django
  version: latest


env_variables:
  DJANGO_SETTINGS_MODULE: "sample_project.settings"